# config/config.yaml

# S3 Settings (for outputs/models)
s3:
  bucket: "bale"              # S3 bucket name
  dataset_path: "dataset/"    # Base path for datasets on local server
  outputs_path: "outputs/"    # Base path for outputs on S3
  subdirs:
    frames: "frames/"         # Subdirectory for frames (local server)
    audio: "audio/"           # Subdirectory for audio (local server)
    models: "models/"         # Subdirectory for models (S3)
    plots: "plots/"           # Subdirectory for plots (S3)
    logs: "logs/"             # Subdirectory for logs (S3)
    results: "results/"       # Subdirectory for results (S3)

# Hyperparameters
training:
  batch_size: 16              # Number of samples per batch (adjustable)
  learning_rate: 0.001        # How fast the model learns
  num_epochs: 10              # Number of training rounds
  fusion_types:               # Which fusion strategies to use
    - "early"
    - "mid"
    - "late"
  dropout_rate: 0.3           # Prevent overfitting (30% dropout)

# Model Settings
models:
  audio:
    input_size: [1, 128, 128] # Spectrogram size (channels, height, width)
    output_dim: 128           # Feature vector size
  image:
    input_size: [3, 224, 224] # Image size (channels, height, width)
    output_dim: 128           # Feature vector size
  emotions:
    num_classes: 7            # Emotions: happy, sad, angry, etc.

# Memory Management
memory:
  max_usage_percent: 80       # Max memory usage (80%)
  target_usage_percent: 70    # Target usage for batch sizing (70%)

# Miscellaneous
logging:
  log_frequency: 10           # Log every 10 batches