# config/config.yaml

# Local Filesystem Settings
local:
  dataset_path: "dataset/"    # Base path for datasets
  outputs_path: "outputs/"    # Base path for outputs
  test_data_path: "test_data/" # Base path for test videos
  subdirs:
    frames: "frames/"         # Subdirectory for frames
    audio: "audio/"           # Subdirectory for audio
    models: "models/"         # Subdirectory for models
    plots: "plots/"           # Subdirectory for plots
    logs: "logs/"             # Subdirectory for logs
    results: "results/"       # Subdirectory for results

# Hyperparameters
training:
  batch_size: 16              # Number of samples per batch (adjustable)
  learning_rate: 0.001        # How fast the model learns
  num_epochs: 10              # Number of training rounds
  fusion_types:               # Which fusion strategies to use
    - "early"
    - "mid"
    - "late"
  dropout_rate: 0.3           # Prevent overfitting (30% dropout)

# Model Settings
models:
  audio:
    input_size: [1, 128, 128] # Spectrogram size (channels, height, width)
    output_dim: 128           # Feature vector size
  image:
    input_size: [3, 224, 224] # Image size (channels, height, width)
    output_dim: 128           # Feature vector size
  emotions:
    num_classes: 7            # Emotions: happy, sad, angry, etc.

# Memory Management
memory:
  max_usage_percent: 80       # Max memory usage (80%)
  target_usage_percent: 70    # Target usage for batch sizing (70%)

# Miscellaneous
logging:
  log_frequency: 10           # Log every 10 batches